name: linter-check
on: push
jobs:
  my-job:
    runs-on: macos-11
    steps:
      - name: npm install
        run: |
            make install
        env:
          CI: true
      - name: Run linter
        run: make lint