name: linter-check
on: push
jobs:
  my-job:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        run: |
            make install
      - name: Run linter
        run: make lint